apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trabajos-ingress
  namespace: trabajos
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "api-gateway"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.nexojobs.local
        - auth.nexojobs.local
      secretName: trabajos-tls
  rules:
    - host: api.nexojobs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
    - host: auth.nexojobs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
