apiVersion: v1
kind: ConfigMap
metadata:
  name: trabajos-config
  namespace: trabajos
data:
  KEYCLOAK_PUBLIC_URL: "http://localhost:18080"
  KEYCLOAK_ISSUER_URL: "http://localhost:18080/realms/nexojobs"
