apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: trabajos
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: notifier
  namespace: trabajos
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30081
